version: 2
updates:
  # Docker updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python updates (both requirements.txt and requirements-dev.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      prod-deps:
        patterns:
          - "requirements.txt"
      dev-deps:
        patterns:
          - "requirements-dev.txt"
